services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    environment:
      POSTGRES_USER: minitwit
      POSTGRES_PASSWORD: minitwit
      POSTGRES_DB: minitwit
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minitwit"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-app
      args:
        GO_VERSION: "1.25.0"
    environment:
      DB_ADDR: db
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile-test
      args:
        GO_VERSION: "1.25.0"
    depends_on:
      - web
    entrypoint: ["python3", "./test/minitwit_simulator.py", "http://web:5001/api"]
