##################################################
# WAIT FOR APT TO BE READY
##################################################

- name: Wait for apt lock to be released
  shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      echo "Waiting for apt lock..."
      sleep 5
    done
  changed_when: false
  no_log: true

- name: Wait for unattended upgrades to finish
  shell: |
    while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
      echo "Waiting for apt lists lock..."
      sleep 5
    done
  changed_when: false
  no_log: true
  
- name: Fix interrupted dpkg
  command: dpkg --configure -a
  ignore_errors: yes
  no_log: true

- name: Clean apt cache
  command: apt-get clean
  no_log: true

- name: Update apt cache
  apt:
    update_cache: yes
    lock_timeout: 120
  no_log: true

##################################################
# Install Docker properly
##################################################

- name: Remove conflicting Docker packages
  apt:
    name:
      - containerd
      - containerd.io
      - docker
      - docker-engine
      - docker.io
      - runc
    state: absent
    purge: yes
  ignore_errors: yes
  no_log: true

- name: Install Docker dependencies
  apt:
    name:
      - docker.io
      - docker-compose
      - containerd
      - python3-pip
    state: present
    lock_timeout: 120
  no_log: true

- name: Install Docker Python SDK
  pip:
    name: docker
  no_log: true

- name: Create docker cli-plugins directory
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'
  no_log: true

- name: Install Docker Compose plugin
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'
  no_log: true

- name: Install Docker Buildx plugin
  get_url:
    url: https://github.com/docker/buildx/releases/download/v0.31.1/buildx-v0.31.1.linux-amd64
    dest: /usr/libexec/docker/cli-plugins/docker-buildx
    mode: '0755'
  #no_log: true

##################################################
# Configure containerd properly
##################################################

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
  no_log: true

- name: Generate containerd config
  command: containerd config default
  register: containerd_config
  changed_when: false
  no_log: true

- name: Write containerd config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
  no_log: true

##################################################
# Create image in dockerhub
##################################################

- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "{{ DOCKERHUB_USERNAME }}" # username for dockerhub
    password: "{{ DOCKERHUB_TOKEN }}" # docker token for docker hub
  delegate_to: localhost  # runs on local machine
  become: no 

- name: Build DB image
  community.docker.docker_image:
    name: "{{DOCKERHUB_USERNAME}}/minitwit-db:latest"
    build:
      path: "{{ playbook_dir }}/../"
      dockerfile: docker/Dockerfile-db
    source: build
    push: yes
  delegate_to: localhost  # builds and pushes from local machine
  become: no
  when: inventory_hostname == "dbserver"
  no_log: true

- name: Build APP image
  community.docker.docker_image:
    name: "{{DOCKERHUB_USERNAME}}/minitwit:latest"
    build:
      path: "{{ playbook_dir }}/../"
      dockerfile: docker/Dockerfile-app
      args:
        GO_VERSION: "1.25.0"
    source: build
    push: yes
  delegate_to: localhost  # builds and pushes from local machine
  become: no
  when: inventory_hostname == "webserver"
  no_log: true

##################################################
# Start container services
##################################################

- name: Start and enable containerd
  systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes
  no_log: true

- name: Start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  no_log: true

##################################################
# DB server tasks
##################################################

- name: Create DB directory
  file:
    path: /opt/minitwit-db
    state: directory
  when: inventory_hostname == "dbserver"
  no_log: true

- name: Create docker directory
  file:
    path: /opt/minitwit-db/docker
    state: directory
  when: inventory_hostname == "dbserver"
  no_log: true

- name: Create db directory
  file:
    path: /opt/minitwit-db/db
    state: directory
  when: inventory_hostname == "dbserver"
  no_log: true

# - name: Pull project from Git
#   git:
#     repo: https://github.com/yourrepo/minitwit.git
#     dest: /opt/minitwit
#     version: main

- name: Copy docker compose file to DB server
  copy:
    src: "{{ playbook_dir }}/../docker-compose-db.yaml"
    dest: /opt/minitwit-db/
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname == "dbserver"
  notify: restart db 
  no_log: true

- name: Copy docker files to DB server
  copy:
    src: "{{ playbook_dir }}/../docker/Dockerfile-db"
    dest: /opt/minitwit-db/docker/Dockerfile-db
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname == "dbserver"
  no_log: true

- name: Copy Schema SQL to DB server
  copy:
    src: "{{ playbook_dir }}/../db/schema.sql" 
    dest: /opt/minitwit-db/db/schema.sql
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname == "dbserver"
  no_log: true


- name: Start DB container
  community.docker.docker_compose_v2:
    project_src: /opt/minitwit-db
    files:
      - docker-compose-db.yaml
    state: present
    build: always
  when: inventory_hostname == "dbserver"
  no_log: true

##################################################
# App playbook tasks
##################################################

- name: Create application directory
  file:
    path: /opt/minitwit
    state: directory
    mode: '0755'
  when: inventory_hostname == "webserver"
  no_log: true

- name: Copy docker compose file to Web server
  copy:
    src: "{{ playbook_dir }}/../docker-compose-app.yaml"
    dest: /opt/minitwit
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname == "webserver"
  notify: restart web
  no_log: true

- name: Start Web container
  community.docker.docker_compose_v2:
    project_src: /opt/minitwit
    files:
      - docker-compose-app.yaml
    state: present
  when: inventory_hostname == "webserver"
  no_log: true