- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose-plugin
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK
  pip:
    name: docker

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create DB directory
  file:
    path: /opt/minitwit-db
    state: directory

- name: Copy docker-compose-db.yaml
  copy:
    src: "{{ playbook_dir }}/../docker-compose-db.yaml"
    dest: /opt/minitwit-db/docker-compose-db.yaml
  notify: restart db container

- name: Start DB container
  community.docker.docker_compose_v2:
    project_src: /opt/minitwit-db
    files:
      - docker-compose-db.yaml
    state: present