##courtesy to jheise for providing the original starting point from which this Dockerfile has developed: https://github.com/jheise/ubuntu-golang/blob/master/Dockerfile
FROM ubuntu:24.04

ARG GO_VERSION
ENV GO_VERSION=${GO_VERSION}

# Installation phase
RUN apt-get update && apt-get install -y \
    wget \
    git \
    gcc \
    ca-certificates \
    python3 \
    python3-pip \
    python3.12-venv \
    && rm -rf /var/lib/apt/lists/*

# Dynamically detect architecture and download the correct Go binary
RUN set -eux; \
    arch="$(dpkg --print-architecture)"; \
    case "${arch}" in \
        amd64) export GO_ARCH='amd64' ;; \
        arm64) export GO_ARCH='arm64' ;; \
        armhf) export GO_ARCH='armv6l' ;; \
        i386)  export GO_ARCH='386' ;; \
        *) echo "Unsupported architecture: ${arch}"; exit 1 ;; \
    esac; \
    wget -O /tmp/go.tar.gz "https://dl.google.com/go/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz"; \
    tar -C /usr/local -xzf /tmp/go.tar.gz; \
    rm /tmp/go.tar.gz

# Setup Go environment
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# Set working directory
WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

# RUN mkdir /minitwit-tests/
# COPY test/requirements.txt /minitwit-tests/
# COPY test/minitwit_simulator.py /minitwit-tests/


COPY . .
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install -r ./test/requirements.txt
RUN go build -o minitwit .

EXPOSE 5001


CMD ["./minitwit"]

RUN python3 ./test/minitwit_simulator.py 5001
