- name: Install required system packages
  apt:
    name:
      - docker.io
      - docker-compose-plugin
      - rsync
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker Python module
  pip:
    name: docker

- name: Install Docker Compose Python module
  pip:
    name: docker-compose

- name: Ensure docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create application directory
  file:
    path: /opt/minitwit # standard directory in Linux for add-on software applications
    state: directory
    mode: '0755' # I am not sure about this

- name: Copy project files
  synchronize:
    src: "{{ playbook_dir }}/../"
    dest: /opt/minitwit
    delete: yes
  notify: restart docker compose

- name: Start Docker Compose stack
  command: docker compose up -d --build
  args:
    chdir: /opt/minitwit